services:
  - type: web
    name: zero-confusion-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook.py"
    envVars:
      - key: PORT
        value: 5000
